# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build app

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"

      - name: Restore the node modules
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: modules-${{ hashFiles('**/package.json') }}

      - name: Install dependencies
        run: yarn install

      - name: Build the app
        run: CI=false npm run build-ghpages

      - run: touch ./build/.nojekyll

      - name: GH Pages Deployment
        uses: JamesIves/github-pages-deploy-action@4.1.3
        if: ${{ github.ref == 'refs/heads/master'}}
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: ./build
          clean: true # Automatically remove deleted files from the deploy branch
